# Generated by Django 6.0.6 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
